# Generated by Django 4.1.1 on 2022-10-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Malumotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('who', models.CharField(max_length=500)),
                ('bolim', models.CharField(max_length=500)),
                ('kimga', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('chat_id', models.PositiveBigIntegerField()),
                ('data', models.DateField(auto_now=True)),
            ],
        ),
    ]
